name: eurek-ai/tudu-dal package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@1catano"
      - run: npm install
      - run: chmod +x install_dev_dependencies.bash
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_USER_TOKEN }}
